apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
        - name: welcome
          image: iram1234/welcome-to-docker:latest
          ports:
            - containerPort: 80
